### ISSUE TITLE
Question: Generate token decryptable by the container

### ISSUE THREAD

**Issue by pierreis** [auth0/wt-cli#161] opened 2017-10-03 18:45 UTC
I'm trying to build a deployment and configuration tool based on Webtask. The requirements are as follows:

– During the configuration phase, the client enters its credentials for various services, possibly with multiple successive commands
– The application is later deployed
– When running, the application should have access to the decrypted credentials

The basic idea would be to generate tokens calling the API during the generation phase to create tokens. The tokens would be inserted in a configuration file deployed along with the application. The application would be passed (as secret) another token allowing it to decrypt the tokens by calling the token inspect API.

My problem is that I can't generate on the client a token with a `dd` claim of 1.

```
→ wt-cli token inspect `wt-cli token create --dd 1`
Token.ca:    [ '...',
  '...' ]
Token.dd:    0
Token.iat:   1507056012
Token.jti:   ...
Token.ten:   /^wt-baf19f40bc985f328b1d25d358fd38fd-[0-1]$/
```

I guess the explanation is that the authorizing token itself from `~/.webtask` has a `dd` equaling 1. 

Yet, I can't find a way to initialize `wt-cli` with a `dd` higher than 1. Any tips on that?

**Comment by ggoodman** [comment] 2017-10-04 14:17
Hi @pierreis, on our freemium [Auth0 Extend](https://auth0.com/extend/developers) deployment on webtask.io, we do not issue users tokens with `dd > 1` by design.

Can you join our [Slack team](https://skynet.run.webtask.io/webtask-signup)? We'd like to get a better understanding of your requirements.

I'm closing this issue because I don't believe there is a `wt-cli` bug. Please join us on Slack to continue the discussion.

**Closed by ggoodman** 2017-10-04 14:17 UTC
Labels: question
