### ISSUE TITLE
It would be nice if we can have a command/option to change the default profile

### ISSUE THREAD

**Issue by mcastany** [auth0/wt-cli#64] opened 2016-06-11 01:03 UTC
If you don't specify --profile, wt uses the default profile. It would be nice if we could switch the default profile, without having to override the previous one. (e.g. `wt profile get 'profile-name' --set-default`)

**Comment by rwtombaugh** [comment] 2018-02-06 01:56
This is a duplicate of https://github.com/auth0/wt-cli/issues/159

**Closed by rwtombaugh** 2018-02-06 01:56 UTC
